# Database Configuration
database:
  host: "localhost"       # MySQL server hostname
  port: 3306               # MySQL server port
  dbname: "groupdungeon"  # Database name
  user: "dungeon_user"    # Database user
  password: "strong_password" # Database password
  pool-size: 10            # Maximum connections in the pool
  table-prefix: ""        # Optional prefix for table names

# Debug Settings
debug: true

# General Settings
settings:
  # Maximum number of dungeons per category to show in GUI
  max_dungeons_per_category: 14
  
  # Whether to check party requirements
  check_party_requirements: true
  
  # Whether to check level requirements
  check_level_requirements: true
